# @format

name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  # 直近のコミットについて、cdkもしくはnotion_apiディレクトリに変更があった場合にのみ実行する
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      IS_CHANGED: ${{ steps.check_cdk.outputs.CDK_CHANGED == 'true' || steps.check_notion_api.outputs.SRC_CHANGED == 'true' }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Check cdk changes
        id: check_cdk
        run: |
          if git diff --quiet HEAD^ cdk; then
            echo CDK_CHANGED=false >> $GITHUB_OUTPUT
          else
            echo CDK_CHANGED=true >> $GITHUB_OUTPUT
          fi

      - name: Check notion_api changes
        id: check_notion_api
        run: |
          if git diff --quiet HEAD^ notion_api; then
            echo SRC_CHANGED=false >> $GITHUB_OUTPUT
          else
            echo SRC_CHANGED=true >> $GITHUB_OUTPUT
          fi

  deploy:
    needs: check_changes
    if: ${{ needs.check_changes.outputs.IS_CHANGED == 'true' }}
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Generate Lambda Layer
        uses: koboriakira/gh-actions/aws/generate-lambda-layer@main
        with:
          python-version: "3.12"

      - name: CDK Deploy
        uses: koboriakira/gh-actions/aws/deploy_cdk@main
        with:
          workdir: cdk
          aws-role: ${{ secrets.AWS_ROLE }}
        env:
          NOTION_SECRET: ${{ secrets.NOTION_SECRET }}
          UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_USER_TOKEN: ${{ secrets.SLACK_USER_TOKEN }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LAMBDA_SLACK_CONCIERGE_API_DOMAIN: ${{ secrets.LAMBDA_SLACK_CONCIERGE_API_DOMAIN }}
          LAMBDA_TWITTER_API_DOMAIN: ${{ secrets.LAMBDA_TWITTER_API_DOMAIN }}
          LAMBDA_GOOGLE_CALENDAR_API_DOMAIN: ${{ secrets.LAMBDA_GOOGLE_CALENDAR_API_DOMAIN }}
          LAMBDA_GOOGLE_CALENDAR_API_ACCESS_TOKEN: ${{ secrets.LAMBDA_GOOGLE_CALENDAR_API_ACCESS_TOKEN }}
